# 47장. 에러 처리

## 47.1 에러 처리의 필요성

- 에러가 발생하지 않는 코드를 작성하는 것은 불가능
- 발생한 에러에 대해 대처하지 않고 방치하면, 프로그램은 강제 종료됨

- **에러 발생**

  - `try ... catch`
  - 에러 발생시 프로그램이 강제 종료되지 않고 계속해서 코드를 실행시킬 수 있다

  ```javascript
  console.log('[Start]');
  
  try {
    foo();
  } catch (error) {
    console.error('[에러 발생]', error);
    // [에러 발생] ReferenceError: foo is not defined
  }
  ```

- **예외적인 상황 발생**
  - 에러를 발생시키지는 않음
  - 하지만 적절히 대응하지 않으면 에러로 이어질 가능성 높음
- 에러와 예외적인 상황이 없는 코드를 작성하는 것은 불가능하다
  - 따라서 언제나 에러나 예외적인 상황이 발생할 수 있다는 것을 전제하고 이에 대응하는 코드를 작성하는 것이 중요

## 47.2 `try .. catch ... finally` 문

- 에러 처리를 구현하는 두 가지 방법

  1. 예외적인 상황이 발생하면 반환하는 값을 if 문이나 단축 평가 또는 옵셔널 체이닝 연산자를 통해 확인해서 처리하는 방법
  2. 에러 처리 코드를 미리 등록해 두고 에러가 발생하면 에러 처리 코드로 점프하도록 하는 방법

- `try ... catch ... finally` 문은 에러 처리 코드를 미리 등록하고, 에러 발생시 에러 처리 코드로 점프하도록 하는 방법

  - `catch`, `finally`는 생략 가능
  - 하지만 `catch`를 생략하면 의미가 없으므로 생략하지 않는다

  ```javascript
  try {
    // 실해할 코드(에러가 발생할 가능성이 있는 코드)
    foo();
  } catch (err) {
    // try 코드 블록에서 에러가 발생하면 이 코드 블록의 코드가 실행
    // err에는 try 코드 블록에서 발생한 Error 객체가 전달
    console.log(err); // ReferenceError: foo is not defined
  } finally {
    // 에러 발생과 상관없이 반드시 한 번 실행
    console.log('finally')
  }
  
  // try...catch...finally 문으로 에러 처리시 프로그램이 강제로 종료되지 않음
  console.log('[End]'); // [End]
  ```



## 47.3 Error 객체

```javascript
const error = new Error('invalid');
```



## 47.4 `throw`문



## 47.5 에러의 전파

